#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TAILLE_SCORE 5

#define GRAVITE 0.2
#define SAUT_VELOCITE -5

#define COTE_VELOCITE 0.3 
#define MAX_COTE_VELOCITE 4.0
#define FROTTEMENT_COTE 0.1

#define VITESSE_MAX 3

#define SCALE_PERSO 1

#define NB_PLATEFORMES 5

#define PLAYER_SPRITE_WIDTH 64
#define PLAYER_SPRITE_HEIGHT 64

#define MIN_X_PLATEFORME 10
#define MAX_X_PLATEFORME 180

#define MIN_VX_PLATEFORME 2
#define MAX_VX_PLATEFORME 3

#define TRAMPOLINE_VELOCITE -15

#endif // CONSTANTS_H
